#!/usr/bin/env python3
"""Bundle the material-osc Lua sources into one deployable script."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_SOURCE_DIR = ROOT / "src"
ENTRY_FILE = DEFAULT_SOURCE_DIR / "main.lua"
FONTS_DIR = ROOT / "fonts"
BUILD_DIR = ROOT / "build"
ENTRY_MARKER = "-- ===== material-osc entry point ====="
GENERATED_HEADER = "-- Generated by bundle.py. Do not edit this file directly."
SYMBOL_FONT = "MaterialSymbolsRoundedUnfilled.ttf"
LUA_STRING = re.compile(r'''["']([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)?)["']''')


def module_name(path: Path, source_dir: Path) -> str:
    relative = path.relative_to(source_dir.parent).with_suffix("")
    return ".".join(relative.parts)


def read_entry_point(entry_file: Path) -> str:
    """Read the hand-written entry point."""
    if not entry_file.is_file():
        raise FileNotFoundError(
            f"Entry point not found: {entry_file}"
        )

    contents = entry_file.read_text(encoding="utf-8")
    if ENTRY_MARKER in contents:
        contents = contents.split(ENTRY_MARKER, 1)[1]
    return contents.lstrip("\r\n")


def build_bundle(source_dir: Path, entry_file: Path) -> tuple[str, int]:
    entry_point = read_entry_point(entry_file)
    lua_files = sorted(
        path for path in source_dir.rglob("*.lua") if path.resolve() != entry_file.resolve()
    )
    if not lua_files:
        raise FileNotFoundError(f"No Lua modules found under {source_dir}")

    sections = [GENERATED_HEADER, ""]
    for path in lua_files:
        name = module_name(path, source_dir)
        source = path.read_text(encoding="utf-8").rstrip()
        sections.extend(
            (
                f"-- ===== {path.relative_to(ROOT).as_posix()} =====",
                f'package.preload["{name}"] = function(...)',
                source,
                "end",
                "",
            )
        )

    sections.extend((ENTRY_MARKER, entry_point.rstrip(), ""))
    return "\n".join(sections), len(lua_files)


def embed_version(bundle: str, version: str) -> str:
    marker = "__MATERIAL_OSC_VERSION__"
    if marker not in bundle:
        raise RuntimeError("Updater version marker was not found in the bundle")
    lua_version = version.replace("\\", "\\\\").replace('"', '\\"')
    return bundle.replace(marker, lua_version)


def subset_symbol_font(source_dir: Path, source_font: Path, output_font: Path) -> int:
    """Keep only Material Symbol ligatures referenced by the Lua sources."""
    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
    except ImportError as error:
        raise RuntimeError(
            "FontTools is required to build the icon subset. "
            "Install build dependencies with: pip install -r requirements-build.txt"
        ) from error

    font = TTFont(source_font)
    glyph_order = set(font.getGlyphOrder())
    candidates: set[str] = set()
    for lua_file in source_dir.rglob("*.lua"):
        candidates.update(LUA_STRING.findall(lua_file.read_text(encoding="utf-8")))
    icons = sorted(candidates & glyph_order)
    if not icons:
        raise RuntimeError("No Material Symbol icon names were found in the Lua sources")

    best_cmap = font.getBestCmap() or {}
    glyphs = set(icons)
    for icon in icons:
        for character in icon:
            glyph = best_cmap.get(ord(character))
            if glyph:
                glyphs.add(glyph)

    options = subset.Options()
    options.layout_features = ["rlig"]
    options.layout_closure = False
    options.glyph_names = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.name_IDs = ["*"]
    options.name_languages = ["*"]

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(glyphs=glyphs)
    subsetter.subset(font)
    output_font.parent.mkdir(parents=True, exist_ok=True)
    font.save(output_font)
    return len(icons)


def build_fonts(source_dir: Path, destination_fonts: Path) -> tuple[int, int, int]:
    if destination_fonts.exists():
        shutil.rmtree(destination_fonts)
    destination_fonts.mkdir(parents=True)

    source_symbol_font = FONTS_DIR / SYMBOL_FONT
    if not source_symbol_font.is_file():
        raise FileNotFoundError(f"Material Symbols source font not found: {source_symbol_font}")
    output_symbol_font = destination_fonts / SYMBOL_FONT
    icon_count = subset_symbol_font(source_dir, source_symbol_font, output_symbol_font)

    for font in FONTS_DIR.iterdir():
        if font.is_file() and font.name != SYMBOL_FONT:
            shutil.copy2(font, destination_fonts / font.name)
    return icon_count, source_symbol_font.stat().st_size, output_symbol_font.stat().st_size


def validate_version(version: str) -> str:
    if not version or version in {".", ".."} or Path(version).name != version:
        raise argparse.ArgumentTypeError(
            "version must be a single non-empty directory name"
        )
    return version


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a versioned, deployable material-osc build."
    )
    parser.add_argument(
        "version", type=validate_version,
        help="version directory to create under build/ (for example, 1.2.0)",
    )
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    destination = BUILD_DIR / args.version
    output = destination / "material-osc.lua"
    destination.mkdir(parents=True, exist_ok=True)

    bundle, module_count = build_bundle(source_dir, ENTRY_FILE)
    bundle = embed_version(bundle, args.version)
    output.write_text(bundle, encoding="utf-8", newline="\n")

    legacy_fonts = destination / "fonts"
    if legacy_fonts.exists():
        shutil.rmtree(legacy_fonts)
    icon_count, source_font_size, subset_font_size = build_fonts(
        source_dir, destination / "material-osc"
    )
    print(
        f"Built material-osc {args.version} with {module_count} modules and "
        f"{icon_count} icons in {destination}"
    )
    print(
        f"Subset {SYMBOL_FONT}: {source_font_size // 1024} KiB -> "
        f"{subset_font_size // 1024} KiB"
    )


if __name__ == "__main__":
    main()
