#!/usr/bin/env python3
"""Bundle the material-osc Lua sources into one deployable script."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_SOURCE_DIR = ROOT / "src"
ENTRY_FILE = DEFAULT_SOURCE_DIR / "main.lua"
FONTS_DIR = ROOT / "fonts"
BUILD_DIR = ROOT / "build"
ENTRY_MARKER = "-- ===== material-osc entry point ====="
GENERATED_HEADER = "-- Generated by bundle.py. Do not edit this file directly."


def module_name(path: Path, source_dir: Path) -> str:
    relative = path.relative_to(source_dir.parent).with_suffix("")
    return ".".join(relative.parts)


def read_entry_point(entry_file: Path) -> str:
    """Read the hand-written entry point."""
    if not entry_file.is_file():
        raise FileNotFoundError(
            f"Entry point not found: {entry_file}"
        )

    contents = entry_file.read_text(encoding="utf-8")
    if ENTRY_MARKER in contents:
        contents = contents.split(ENTRY_MARKER, 1)[1]
    return contents.lstrip("\r\n")


def build_bundle(source_dir: Path, entry_file: Path) -> tuple[str, int]:
    entry_point = read_entry_point(entry_file)
    lua_files = sorted(
        path for path in source_dir.rglob("*.lua") if path.resolve() != entry_file.resolve()
    )
    if not lua_files:
        raise FileNotFoundError(f"No Lua modules found under {source_dir}")

    sections = [GENERATED_HEADER, ""]
    for path in lua_files:
        name = module_name(path, source_dir)
        source = path.read_text(encoding="utf-8").rstrip()
        sections.extend(
            (
                f"-- ===== {path.relative_to(ROOT).as_posix()} =====",
                f'package.preload["{name}"] = function(...)',
                source,
                "end",
                "",
            )
        )

    sections.extend((ENTRY_MARKER, entry_point.rstrip(), ""))
    return "\n".join(sections), len(lua_files)


def validate_version(version: str) -> str:
    if not version or version in {".", ".."} or Path(version).name != version:
        raise argparse.ArgumentTypeError(
            "version must be a single non-empty directory name"
        )
    return version


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a versioned, deployable material-osc build."
    )
    parser.add_argument(
        "version", type=validate_version,
        help="version directory to create under build/ (for example, 1.2.0)",
    )
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    destination = BUILD_DIR / args.version
    output = destination / "material-osc.lua"
    destination.mkdir(parents=True, exist_ok=True)

    bundle, module_count = build_bundle(source_dir, ENTRY_FILE)
    output.write_text(bundle, encoding="utf-8", newline="\n")

    destination_fonts = destination / "fonts"
    if destination_fonts.exists():
        shutil.rmtree(destination_fonts)
    shutil.copytree(FONTS_DIR, destination_fonts)

    print(f"Built material-osc {args.version} with {module_count} modules in {destination}")


if __name__ == "__main__":
    main()
